### ISSUE TITLE
모바일 가시성 문제

### ISSUE THREAD

**Issue by raven724** [SKKU-SWForum/School_FAQs#11]
현재 사이트가 모바일에서는 일부 내용이 잘리는 현상이 발생합니다.
대처가 가능한지 여부를 파악하는 것이 필요하다고 봅니다.

**Comment by daniel2231** [comment]
어떤 부분이 잘리는지 알려주실 수 있나요? @raven724

**Comment by raven724** [comment]
표가 길어지면 잘리닌 것 같습니다.
사이트 문제인거 같습니다.

**Comment by raven724** [comment]
모바일 뿐만 아니라 13인치 맥북 프로에서도 같은 증상 확인.
리뉴얼 가능한지 여부 분석 필요한 것으로 보임.

**Comment by raven724** [comment]
페이지 테마 리뉴얼 계획에 따라 해당 Issue Close #34
