### ISSUE TITLE
이미지 출력 문제

### ISSUE THREAD

**Issue by raven724** [SKKU-SWForum/School_FAQs#12]
기존 파일에서 이미지가 출력되지 않는 현상이 있습니다.
![image](https://user-images.githubusercontent.com/39472872/116491618-41c71a80-a8d5-11eb-8606-91eb49f79ea7.png)

**Comment by daniel2231** [comment]
![image](https://user-images.githubusercontent.com/39212398/116571170-cbaecc00-a945-11eb-9f7f-cb2bd0c392ad.png)

해결 방법을 찾은 것 같습니다. 파일 경로가 잘못된 것 같더군요. 위처럼 바꾸고 Image 폴더명을 image로 바꿨습니다. image-fix 브랜치를 파서 PR 날리겠습니다. @raven724

**Comment by daniel2231** [comment]
#15 

이미지 폴더를 "Image"에서 "image"로 바꾼거 참고 부탁드립니다.

**Comment by raven724** [comment]
제가 갈통이었군요 ㅋㅋ;; 감사드립니다.

**Comment by daniel2231** [comment]
흠 적용되었는데 안되네요... 테스트 환경에서는 됐는데 저기서 안되는거 보면 또 다른 문제가 있는가봅니다.

**Comment by raven724** [comment]
아무래도 더 들여다 봐야할 것 같습니다. 사진이 아예 안넘어가는 것일 수도 있고요...

**Comment by daniel2231** [comment]
https://skkuoverflow.com/posts/linux/Images/ls.png

이미지 폴더를 "image"로 바꿔줘야 할 것 같아요 ㅎㅎ

**Comment by raven724** [comment]
해결했습니다. 사진은 static 디렉토리에 넣고 관리하면 해결되네요.
README.md에 추가로 설명 달겠습니다. 도와주셔서 감사합니다. @daniel2231

**Comment by daniel2231** [comment]
아 근데 그렇게 하면 관리하기가 힘들지 않나요?

**Comment by raven724** [comment]
큰 시리즈마다 폴더를 만들면 괜찮을 것 같습니다.

**Comment by daniel2231** [comment]
아직 이미지가 안나오는 것 같은데, 아직 적용이 안된건가요?

**Comment by raven724** [comment]
원인 찾고 대응하겠습니다.

**Comment by raven724** [comment]
해결했습니다. 사용 방법도 readme에 적어놓겠습니다.
