### ISSUE TITLE
포스트 이미지

### ISSUE THREAD

**Issue by daniel2231** [SKKU-SWForum/School_FAQs#14]
![image](https://user-images.githubusercontent.com/39212398/116497110-8d7fc100-a8e1-11eb-9008-90a3fc539c3c.png)

포스트 이미지가 없기에 이것도 한번 만들어봤습니다.

**Comment by raven724** [comment]
확인했습니다. 감사합니다. 다만 아직 이미지 추가를 어떻게 하는지 확인중이라 최대한 빠르게 넣겠습니다.

**Comment by daniel2231** [comment]
이 부분 제가 한번 해볼까요? @raven724

**Comment by raven724** [comment]
네 기여해주셔도 됩니다.

**Comment by daniel2231** [comment]
페이지 번들링 문제인가 해서 폴더를 다시 구성해봐도 안되고, static에 넣어도 안되네요.

일단 static 넣는건 옳지 않은 방법인 것 같습니다.

여태까지 삽질(?)한 것들을 공유하겠습니다.

테마 폴더도 한번 뜯어봐서 봤는데 아래의 helper 코드가 있습니다.
```
{{/* check if there is any hero image in the same folder as the markdown file */}}
{{ $heroImage := .Page.Resources.GetMatch "hero.{jpg,png,svg}"}}

{{/*  if hero image is specified in the page front-matter, then use that  */}}
{{ if .Params.hero }}
  {{ $heroImage = .Page.Resources.GetMatch .Params.hero }}
{{ end }}
{{ .Scratch.Set "heroScratch" $heroImage }}

{{/* if hero image is not provided, then use the default hero image */}}
{{ if not $heroImage }}
  {{ $heroImage := resources.Get "images/default-hero.jpg"}}
  {{ .Scratch.Set "heroScratch" $heroImage }}
{{ end }}

{{ $heroImage := .Scratch.Get "heroScratch" }}

{{/* resize hero image. don't resize if the image is an svg */}}
{{ if and $heroImage (ne $heroImage.MediaType.SubType "svg") }}
  {{ $heroImage := $heroImage.Resize "148x" }}
{{ end }}

{{/*  return the hero image  */}}
{{ return $heroImage.RelPermalink }}
```

위의 코드데로라면 페이지 번들링으로만 hero 이미지가 적용 가능 한 것 같습니다.

Hugo Page Bundling: https://gohugo.io/content-management/page-bundles/

허나 이미지 문제때도 발견한거지만 저희 블로그는 toha에서 제공하는 shortcode가 제대로 작동이 안되는 것 같더군요.

예를 들어 아래와 같이 페이지 번들링을 해봤습니다.
![image](https://user-images.githubusercontent.com/39212398/116779278-54e21200-aab0-11eb-951f-85b3fceea99f.png)

그리고 아래와 같이 shortcode를 이용해서 볼러오면 이미지가 오지 않습니다.
![image](https://user-images.githubusercontent.com/39212398/116779292-675c4b80-aab0-11eb-8457-c7a8eda60923.png)

이미지 경로를 "/posts/linux/cat/images/cat.png"로 해야 이미지가 옵니다.

처음 블로그를 만들때 세팅을 잘못 했다던가, 번들링에 뭔가 문제가 있는 것 같습니다.

**Comment by daniel2231** [comment]
아 찾았습니다!

여태까지 shortcode가 적용 안된 이유는 마크다운 이름이 index가 아니여서였군요....
cat.en.md 를 index.en.md로 바꾸니깐 다 정상 작동 합니다.

![image](https://user-images.githubusercontent.com/39212398/116779584-10f00c80-aab2-11eb-90ca-5d73e8a47703.png)

**Comment by raven724** [comment]
어렵군요 휴고... 잘 못챙겼었는데 계속 관심 가져주셔서 감사합니다.
