### ISSUE TITLE
All Contributors bot 사용 건의

### ISSUE THREAD

**Issue by daniel2231** [SKKU-SWForum/School_FAQs#16]
저희 레포시터리를 좀 더 보기 좋게? 하기 위에 아래의 봇을 추가하는 것을 건의 합니다.

https://allcontributors.org/

지금은 각각 어떤 기여를 했는지 적어놓지만, 레포가 커지고 기여자가 많아질수록 그렇게 하긴 힘들 것 같아 위의 봇을 사용하는 것을 건의하게 되었습니다.

동의하시면 제가 세팅하도록 하겠습니다.

**Comment by raven724** [comment]
기여 봇은 제가 확인해보고 알려드릴게요.

**Comment by raven724** [comment]
혹시 적용 가능하신가요? 제가 설정해야 할 부분이 있을 것 같긴 한데 지금 당장 뭔가 하기에는 제가 너무 바쁘네요...

**Comment by daniel2231** [comment]
넵 제가 한번 해보겠습니다!

**Comment by daniel2231** [comment]
봇 설치 요청이 아마 갔을텐데, 나중에 시간 되시면 확인 부탁 드립니다~

**Comment by raven724** [comment]
확인했고 주로 올릴 것으로 보이는 모든 리포에 적용했습니다. 도움 감사드립니다.

**Comment by raven724** [comment]
설치가 완료되었기 때문에 별도의 issue에서 봇 관련 문의를 받겠습니다.
이 이슈는 닫겠습니다.
