### ISSUE TITLE
봇 테스트

### ISSUE THREAD

**Issue by daniel2231** [SKKU-SWForum/School_FAQs#19]
@all-contributors please add @daniel2231  for bug

**Comment by daniel2231** [comment]
흠, 아직 봇이 추가가 안된듯 합니다.

추가 후 원래는 자동 PR이 왔어야 하는데, 아직 안 온 것 같네요...

**Comment by raven724** [comment]
@all-contributors please add @daniel2231  for bug

**Comment by raven724** [comment]
음... 권한이 없어서인걸까요...?

**Comment by daniel2231** [comment]
아 이건 제가 권한이 없어서 그런거였군요

**Comment by raven724** [comment]
권한 확인해보겠습니다. 잠시만 기다려주세요

**Comment by raven724** [comment]
@daniel2231 권한 확인을 해보려 했는데 별도로 권한을 건드는 부분은 없었습니다. 지금 당장은 어떤게 문제인지 파악하기 어렵네요

**Comment by daniel2231** [comment]
@all-contributors please add @daniel2231 for bug

**Comment by daniel2231** [comment]
아 이제 되는구나

**Comment by daniel2231** [comment]
@all-contributors please add @raven724 for project management

**Comment by daniel2231** [comment]
@all-contributors please add @kdy1 for docs and contents

**Comment by daniel2231** [comment]
@all-contributors please add @daniel for translation and content

**Comment by daniel2231** [comment]
????? 뭐야 저분은 누구지

**Comment by daniel2231** [comment]
@all-contributors please add @daniel2231 for translation and content

이름을 잘못 적었었네요...

**Comment by daniel2231** [comment]
@all-contributors please add @dropfl for translation

**Comment by daniel2231** [comment]
@all-contributors please add @nhjbest22 for examples and content

**Comment by daniel2231** [comment]
모든 분들이 추가 되었습니다. issue 닫겠습니다~
