### ISSUE TITLE
서버 접속 불가

### ISSUE THREAD

**Issue by somehowranker** [SKKU-SWForum/School_FAQs#36]
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256://////
Please contact your system administrator.
Add correct host key in ..../.ssh/known_hosts to get rid of this message.
Offending ECDSA key in ..../known_hosts:4
Host key for [swji.skku.edu]:1398 has changed and you have requested strict checking.
Host key verification failed.

접속이 불가능하고 계속 이 문제가 뜨는데 혹시 어떻게 해결하나요?

**Comment by raven724** [comment]
기존에 인의예지 서버를 접속하신 적이 있으실까요?
접속하신 적이 있으신 경우에는 올해 초 장비 변경으로 인해서 SSH Key가 변경되었고, 그걸 경고하는 것 같습니다.
.ssh/known_hosts에서 인의예지 서버 관련된 부분 지우시면 해결될 것으로 보입니다.
이 부분 추가해두겠습니다.

**다만 최근(올해 3월)에 잘 쓰시다가 갑자기 그런 경우에는 보안 문제가 있을 수도 있습니다. 이런 경우에는 접속하는 공유기 등을 잘 확인해보셔야 할 듯 합니다.**
Reference: https://stackoverflow.com/questions/20840012/ssh-remote-host-identification-has-changed

**Comment by raven724** [comment]
24/04/15 반영 완료
